### ISSUE TITLE
osx compatible software version?

### ISSUE THREAD

**Issue by senadir** [MerAARIZOU/Reseaux-Informatiques-Locaux#1]

**Comment by MerAARIZOU** [comment]
I don't think that there is a version for Mac. There are some alternatives though you can create a virtual Machine using VirtualBox and install Windows on it. Then yo can install on the virtual machine the version I gave you. Otherwise there are some tools that can help you install windows softwares on Mac like Wine.

**Comment by senadir** [comment]
wine wasn't possible because it support older versions of windows that are 32bit and the software is quite buggy, and even space in my mac is very limited right now to install another os, think I will just borrow someone laptop tomorrow and do it
